#version 450

#include "direct_trace_interface.glsl"
#include "sampling.glsl"

layout(local_size_x = 64) in;

// Environment cone sample: initialize this pixel's irradiance.

void main() {
  if (gl_GlobalInvocationID.x >= push_constants.samples.count) {
    return;
  }
  const Direct_sample light_sample =
    push_constants.samples.samples[gl_GlobalInvocationID.x];
  const ivec2 size =
    imageSize(storage_images[push_constants.direct_irradiance_image]);
  const ivec2 pixel = direct_sample_pixel(light_sample, size);
  const Direct_shading_point shading_point =
    direct_shading_point(
      push_constants.scene,
      push_constants.depth_texture,
      push_constants.normal_texture,
      pixel,
      size);
  const vec3 n = shading_point.normal;
  const vec3 w_i =
    make_basis(normalize(push_constants.scene.sun_direction)) *
    square_to_cone(unpackUnorm2x16(light_sample.uv), cos_sun_angular_radius);
  const bool occluded = trace_ray(
    push_constants.rt_block_shape_grid,
    push_constants.rt_block_material_grid,
    push_constants.entities,
    push_constants.entity_head_grid,
    push_constants.entity_mask_grid,
    push_constants.entity_nodes,
    shading_point.ray_origin,
    w_i,
    true);
  const vec3 E = direct_environment_contribution(
    push_constants.scene,
    n,
    shading_point.position.y,
    w_i,
    occluded ? 0.0 : 1.0,
    light_sample.p_cone,
    push_constants.transmittance_texture,
    push_constants.sky_view_lut,
    true);
  imageStore(
    storage_images[push_constants.direct_irradiance_image], pixel, vec4(E, 1.0));
}
