#version 450

#include "descriptors.glsl"
#include "octahedral.glsl"
#include "random.glsl"
#include "sampling.glsl"
#include "rt.glsl"
#include "scene.glsl"
#include "atmosphere/atmosphere.glsl"

layout(local_size_x = 8, local_size_y = 8) in;

layout(push_constant) uniform Push_constants {
  layout(offset = 0) Scene scene;
  layout(offset = 8) uint16_t normal_texture;
  layout(offset = 10) uint16_t depth_texture;
  layout(offset = 12) uint16_t sky_view_lut;
  layout(offset = 14) uint16_t transmittance_texture;
  layout(offset = 16) uint16_t indirect_radiance_image;
  layout(offset = 18) uint16_t indirect_radiance_direction_image;
  layout(offset = 20) uint16_t rng_state_image;
  layout(offset = 22) uint16_t blue_noise_texture;
  layout(offset = 24) Rt_block_grid rt_block_grid;
  layout(offset = 32) Rt_entities entities;
  layout(offset = 40) Rt_entity_grid entity_grid;
  layout(offset = 48) Rt_entity_nodes entity_nodes;
} push_constants;

const int bounce_count = 2;

void main() {
  const ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
  const ivec2 size =
    imageSize(storage_images[push_constants.indirect_radiance_image]);
  if (pixel.x >= size.x || pixel.y >= size.y) {
    return;
  }
  const float depth =
    texelFetch(sampled_images[push_constants.depth_texture], pixel, 0).r;
  if (depth == 0.0) {
    return;
  }
  const vec2 ndc = (vec2(pixel) + 0.5) / vec2(size) * 2.0 - 1.0;
  const vec3 view_ray = vec3(
    -ndc.x * push_constants.scene.zoom.x,
    -ndc.y * push_constants.scene.zoom.y,
    1.0);
  const vec3 camera_position = push_constants.scene.camera_basis[3].xyz;
  const float view_z = push_constants.scene.z_near / depth;
  const vec3 world_position =
    camera_position +
    mat3(push_constants.scene.camera_basis) * (view_ray * view_z);
  const vec3 n =
    oct_decode(
      texelFetch(sampled_images[push_constants.normal_texture], pixel, 0).rg);
  // Assume that sun transmittance is constant around the shaded surface.
  const vec3 sun_direction = push_constants.scene.sun_direction;
  const vec3 E_sun =
    push_constants.scene.sun_irradiance *
    transmittance_along_ray(
      push_constants.transmittance_texture,
      vec3(0.0, r_ground + world_position.y, 0.0),
      sun_direction);
  Random random;
  random.state =
    imageLoad(storage_uimages[push_constants.rng_state_image], pixel).x;
  const ivec2 blue_noise_pixel = pixel % 128;
  const vec3 tangent_ray_direction = normalize(texelFetch(
    sampled_images[push_constants.blue_noise_texture],
    blue_noise_pixel,
    0).rgb * 2.0 - 1.0);
  vec3 rd = make_basis(n) * tangent_ray_direction;
  const vec2 encoded_ray_direction = oct_encode(rd);
  vec2 encoded_hit_normal = oct_encode(-rd);
  vec3 ro = offset_ray_origin(world_position, n);
  vec3 radiance = vec3(0.0);
  vec3 radiance_multiplier = vec3(1.0);
  float ray_length = 1024.0;
  for (int bounce = 0; bounce < bounce_count; ++bounce) {
    Rt_hit hit;
    if (trace_ray(
        push_constants.rt_block_grid,
        push_constants.entities,
        push_constants.entity_grid,
        push_constants.entity_nodes,
        ro,
        rd,
        true,
        hit)) {
      if (bounce == 0) {
        ray_length = hit.t;
        encoded_hit_normal = oct_encode(hit.normal);
      }
      const vec3 hit_position = ro + hit.t * rd;
      const vec3 new_ro = offset_ray_origin(hit_position, hit.normal);
      const float sun_visibility =
        trace_ray(
          push_constants.rt_block_grid,
          push_constants.entities,
          push_constants.entity_grid,
          push_constants.entity_nodes,
          new_ro,
          sun_direction,
          true)
          ? 0.0
          : 1.0;
      const float n_dot_l = max(dot(hit.normal, sun_direction), 0.0);
      radiance +=
        radiance_multiplier *
        (hit.emissivity + hit.albedo / pi * E_sun * sun_visibility * n_dot_l);
      if (bounce + 1 < bounce_count) {
        ro = new_ro;
        rd =
          make_basis(hit.normal) *
          square_to_cosine_hemisphere(
            vec2(random_float(random), random_float(random)));
        radiance_multiplier *= hit.albedo;
      }
    } else {
      radiance +=
        radiance_multiplier *
        FPSPARTY_SAMPLE(
          push_constants.sky_view_lut,
          pack_sky_view_lut_params(
            longitude(rd),
            push_constants.scene.camera_basis[3][1],
            zenith(rd))).rgb;
      break;
    }
  }
  imageStore(
    storage_images[push_constants.indirect_radiance_image],
    pixel,
    vec4(radiance, ray_length));
  imageStore(
    storage_images[push_constants.indirect_radiance_direction_image],
    pixel,
    vec4(encoded_ray_direction, encoded_hit_normal));
  imageStore(
    storage_uimages[push_constants.rng_state_image],
    pixel,
    uvec4(random.state));
}
