#version 450

#include "descriptors.glsl"
#include "numbers.glsl"
#include "atmosphere/atmosphere.glsl"

layout(local_size_x = 8, local_size_y = 8) in;

layout(push_constant) uniform Push_constants {
  layout(offset = 0, row_major) mat4x3 camera_basis;
  layout(offset = 48) vec2 zoom;
  layout(offset = 56) uint16_t albedo_texture;
  layout(offset = 58) uint16_t depth_texture;
  layout(offset = 60) uint16_t sky_view_lut;
  layout(offset = 62) uint16_t radiance_image;
  layout(offset = 64) uint16_t direct_irradiance_texture;
} push_constants;

void main() {
  const ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
  const ivec2 size = imageSize(storage_images[push_constants.radiance_image]);
  if (pixel.x >= size.x || pixel.y >= size.y) {
    return;
  }
  const float depth =
    texelFetch(sampled_images[push_constants.depth_texture], pixel, 0).r;
  if (depth == 0.0) {
    const vec2 ndc = (vec2(pixel) + 0.5) / vec2(size) * 2.0 - 1.0;
    const vec3 view_ray = vec3(
      -ndc.x * push_constants.zoom.x, -ndc.y * push_constants.zoom.y, 1.0);
    const vec3 camera_position = push_constants.camera_basis[3].xyz;
    const vec3 rd = normalize(mat3(push_constants.camera_basis) * view_ray);
    const vec2 lut_texcoord =
      pack_sky_view_lut_params(longitude(rd), camera_position.y, zenith(rd));
    const vec3 radiance =
      FPSPARTY_SAMPLE(push_constants.sky_view_lut, lut_texcoord).rgb;
    imageStore(
      storage_images[push_constants.radiance_image],
      pixel,
      vec4(radiance, 1.0));
    return;
  }
  const vec4 material =
    texelFetch(
      sampled_images[push_constants.albedo_texture], pixel, 0);
  const vec3 direct_irradiance =
    texelFetch(
      sampled_images[push_constants.direct_irradiance_texture],
      pixel,
      0).rgb;
  const vec3 L_e = material.rgb * material.a;
  const vec3 L = L_e + material.rgb / pi * direct_irradiance;
  imageStore(
    storage_images[push_constants.radiance_image],
    pixel,
    vec4(L, 1.0));
}
